language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="melodic" UPSTREAM_WORKSPACE='github:ros-industrial/fanuc#indigo-devel'
    - ROS_DISTRO="melodic" UPSTREAM_WORKSPACE='github:ros-industrial/fanuc#indigo-devel' ROS_REPO=ros-shadow-fixed

install:
  - git clone -b master --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
